export const routesList = {
  aboutUs: "/about-us",
  authorizationError: "/401",
  contactUs: "/contact-us",
  forgotPassword: "/forgot-password",
  help: "/help",
  homePage: "/",
  linkedInSignUp:"/linkedin-signup",
  signIn: "/login",
  signUp: "/sign-up",
  profile:"/profile",
  emailVerification:"/email-verification",
  messages: "/messages",
  myAccount: "/my-account",
  notification: "/notification",
  otpVerify: "/otp-verify",
  pageNotFound: "/404",
  privacyPolicy: "/privacy-policy",
  ratingsAndReviews: "/ratings-and-reviews",
  register: "/register",
  resetPassword: "/reset-password",
  services: "/services",
  subCategories: "/sub-categories",
  testimonials: "/testimonials",
  termsPolicy: "/terms-policy",
  thankYou: "/thank-you",
};

export const as = {
  aboutUs: "about-us",
  authorizationError: "401",
  contactUs: "contact-us",
  forgotPassword: "forgot-password",
  help: "help",
  homePage: "",
  linkedInSignUp:"linkedin-signup",
  signIn: "sign-in",
  signUp:"sign-up",
  emailVerification:"email-verification",
  messages: "messages",
  myAccount: "my-account",
  notification: "notification",
  otpVerify: "otp-verify",
  pageNotFound: "404",
  privacyPolicy: "privacy-policy",
  profile:"Profile",
  ratingsAndReviews: "ratings-and-reviews",
  register: "register",
  resetPassword: "reset-password",
  services: "services",
  subCategories: "sub-categories",
  testimonials: "testimonials",
  termsPolicy: "terms-policy",
  thankYou: "thank-you",
};


export const labels = {
  aboutUs: "About Us",
  authorizationError: "Permission Error",
  categories: "Categories",
  contactUs: "Contact Us",
  emailVerify: "Email Verify",
  faqs: "FAQs",
  forgotPassword: "Forgot Password",
  help: "Help",
  linkedInSignUp:"LinkedIn Signup",
  homePage: "/",
  login: "Login",
  emailVerification:"Email Verification",
  messages: "Messages",
  messagingInfo: "Messaging",
  myAccount: "My Account",
  notification: "Notification",
  otpVerify: "OTP Verify",
  pageNotFound: "Page Not Found",
  profile:"Profile",
  privacyPolicy: "Privacy Policy",
  ratingsAndReviews: "Ratings and Reviews",
  register: "Register",
  resetPassword: "Reset Password",
  services: "Services",
  subCategories: "Sub Categories",
  testimonials: "Testimonails",
  termsPolicy: "Terms & Policy",
  thankYou: "Thank You",
  category: "Category",
  subCategory: "Sub Category",
};

export const apiUrls = {
  generateOtp: `generate-otp/`,
  login:`token/`,
  userRegistration:`users/`,
  linkedin:`linkedin-signup/`,
  forgetPasswordSendOtp:`forget-password-send-otp/`,
  userBasicInfo:"user-basic-info/",
  userBasicInfoUpdate:"update-basic-info/",
  contactUs:`contact-us/`,
  categoriesUserexp:'categories/',
  userSignOut: `logout`,
  forgotPassword: `forget-password/`,
  resetPassword: `reset-password`,
  changeOldPassword: `change-password`,
  myProfile:`my-profile/`,
};

export const unProtectedRoutes = [
  // `${routesList.adDetails}/[slug]/[id]`,
  routesList.aboutUs,
  routesList.authorizationError,
  routesList.categories,
  `${routesList.categories}/[slug]/[category_id]`,
  routesList.contactUs,
  routesList.faqs,
  routesList.forgotPassword,
  routesList.help,
  routesList.homePage,
  routesList.linkedInSignUp,
  routesList.signIn,
  routesList.signUp,
  routesList.emailVerification,
  routesList.otpVerify,
  routesList.pageNotFound,
  routesList.privacyPolicy,
  // routesList.profile,
  routesList.register,
  routesList.resetPassword,
  routesList.subCategories,
  routesList.testimonials,
  routesList.termsPolicy,
  routesList.thankYou,
];
export const userLoginPath =[
  routesList.signIn,
  routesList.signUp,
  routesList.forgotPassword,

]
export const jobSeekerRoutes = [
  
];

export const jobProviderRoutes = [

];